name: Build Infinix Pentest Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev libelf-dev bison flex kmod gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Compile Kernel
      run: |
        # Lilipat tayo sa GCC para iwas conflict sa mga lumang compiler flags ng MediaTek
        export MAKE_FLAGS="ARCH=arm64 \
                           CROSS_COMPILE=aarch64-linux-gnu- \
                           CROSS_COMPILE_ARM32=arm-linux-gnueabi-"
        
        # 1. Load ng defconfig mo
        make O=out $MAKE_FLAGS defconfig
        
        # 2. Sync ng configs para walang prompt
        make O=out $MAKE_FLAGS olddefconfig
        
        # 3. Compile gamit ang GCC
        make O=out $MAKE_FLAGS Image.gz modules -j$(nproc)

    - name: Upload Finished Kernel and Modules
      uses: actions/upload-artifact@v4
      with:
        name: Finished-Infinix-Kernel
        path: |
          out/arch/arm64/boot/Image.gz
          out/drivers/bluetooth/hci_vhci.ko
