name: Build Infinix Pentest Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev libelf-dev bison flex kmod gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi clang lld

    - name: Compile Kernel
      run: |
        # I-setup ang lahat ng kailangang krus na compiler (64-bit at 32-bit)
        export MAKE_FLAGS="ARCH=arm64 \
                           CROSS_COMPILE=aarch64-linux-gnu- \
                           CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                           CC=clang \
                           LD=ld.lld"
        
        # 1. I-load ang bago mong defconfig
        make O=out $MAKE_FLAGS defconfig
        
        # 2. I-sync ang mga lumang configs para walang interactive prompts
        make O=out $MAKE_FLAGS olddefconfig
        
        # 3. I-compile ang kernel image at ang mga modules (-j$(nproc) para gamitin lahat ng core)
        # Gagamitin muna natin ang 'Image.gz' na target imbes na 'Image.gz-dtb' para laktawan ang dts error kung wala ito sa repo
        make O=out $MAKE_FLAGS Image.gz modules -j$(nproc)

    - name: Upload Finished Kernel and Modules
      uses: actions/upload-artifact@v4
      with:
        name: Finished-Infinix-Kernel
        path: |
          out/arch/arm64/boot/Image.gz
          out/drivers/bluetooth/hci_vhci.ko
